# Generated by Django 5.1.2 on 2024-10-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='country_code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='flag_url',
            field=models.URLField(null=True, verbose_name='Flag URL'),
        ),
    ]
