# Generated by Django 5.1.2 on 2024-10-25 08:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'db_table': 'periods',
                'ordering': ('start_date',),
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_rank', models.PositiveIntegerField(db_index=True, null=True)),
                ('previous_rank', models.PositiveIntegerField(db_index=True, null=True)),
                ('current_points', models.DecimalField(decimal_places=5, max_digits=10)),
                ('previous_points', models.DecimalField(decimal_places=5, max_digits=10)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.period')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
    ]
