# Generated by Django 5.1.2 on 2024-10-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=255, unique=True)),
                ('country_code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('flag_url', models.URLField()),
                ('current_rank', models.PositiveIntegerField(db_index=True)),
                ('previous_rank', models.PositiveIntegerField(db_index=True)),
                ('current_points', models.DecimalField(decimal_places=5, max_digits=10)),
                ('previous_points', models.DecimalField(decimal_places=5, max_digits=10)),
                ('confederation', models.CharField(choices=[('UEFA', 'UEFA'), ('AFC', 'AFC'), ('OFC', 'OFC'), ('CONMEBOL', 'CONMEBOL'), ('CAF', 'CAF'), ('CONCACAF', 'CONCACAF'), ('N/A', 'Not Applicable')], db_index=True, default='N/A', max_length=10)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'teams',
                'ordering': ('current_rank',),
            },
        ),
    ]
