# Generated by Django 5.1.2 on 2024-10-25 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
        ('team', '0002_alter_team_country_code_alter_team_flag_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking',
            options={'ordering': ['current_rank']},
        ),
        migrations.AlterField(
            model_name='ranking',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='ranking.period'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='team.team'),
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together={('team', 'period')},
        ),
    ]
