# Generated by Django 5.1.2 on 2024-10-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='current_rank',
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='previous_rank',
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
    ]
