# Generated by Django 5.1.2 on 2024-10-16 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_period_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('coefficient', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Competition',
                'verbose_name_plural': 'Competitions',
                'db_table': 'competitions',
                'ordering': ('name',),
            },
        ),
        migrations.RunSQL(
            sql='''
                INSERT INTO competitions (name, coefficient) 
                VALUES ('World Cup Qualification AFC', 25);
                '''
        ),
        migrations.AddField(
            model_name='game',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ranking.competition'),
            preserve_default=False,
        ),
    ]
