# Generated by Django 5.1.2 on 2024-10-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_alter_competition_coefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='api_id',
            field=models.PositiveIntegerField(db_index=True, null=True, unique=True, verbose_name='API ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='flag_url',
            field=models.URLField(verbose_name='Flag URL'),
        ),
    ]
