# Generated by Django 5.1.2 on 2024-10-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_competition_game_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_points_change',
            field=models.DecimalField(decimal_places=5, default=9.651, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='home_points_change',
            field=models.DecimalField(decimal_places=5, default=-5.352, max_digits=10),
            preserve_default=False,
        ),
    ]
