# Generated by Django 5.1.2 on 2024-10-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0006_game_is_knockout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_points_change',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_points_change',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
